# Generated by Django 4.1.4 on 2022-12-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_identity_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identity",
            name="move_to_redirect",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
